### ISSUE TITLE
Hey RCR software engineers!

### ISSUE THREAD

**Issue by tsarvs** [rcr-software/groundstation_GUI#1]
My name is Tom Sarver, and a couple years ago I did some software development for RCR much like you all are doing. I have since graduated, but I'd like to offer any assistance I can provide if you all need it; be that code reviews, PRs, design discussions, etc. I've been loosely following the progression of some of your repositories, and I'm very curious to see what you all are working on and if there is anything I can do to help.

Feel free to reach out to my email: tom@tomsarver.dev to get in touch

**Comment by jahigd02** [comment]
That's awesome! It's great to hear from an alumni! This code here is very new in development and is very much in need of some code reviews soon, so I really appreciate you reaching out! The code is a little messy right now as we sort out how to get it working with our web server, but I think I will be reaching out very shortly once I sort out an issue.

**Comment by jahigd02** [comment]
Do you have any background in Javascript and/or web backend?

**Comment by tsarvs** [comment]
I do have experience in JS! Lets take this discussion off of this thread, but I'd love to talk more.
